tokens:
  MyUSD:
    supply: 100
    name: MyUSD
    description: Collaterlized Cardano native stablecoinn redeemable for USDT using Mynth.
    url: https://mynth.ai
    logo: mynth-logo.png
    decimals: 6
    policyId: 91d4f382273f442f15e9da48cb23349ba275f8818e4c7ac5d1004a16
wallets:
  minter:
  owner:
