tokens:
  MyUSD:
    supply: 100
    name: MyUSD
    description: Collaterlized Cardano native stablecoinn redeemable for USDT using Mynth.
    url: https://mynth.ai
    logo: mynth-logo.png
    decimals: 6
    policyId: 0c6e170c9dc52bae251312ef4abeb27a0d837899b539c2f3b44afef3
wallets:
  minter:
  owner:
