name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency: cardano-preview
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1

      - name: Update npm
        run: npm install -g npm@9.7.2

      - name: Install dependencies
        run: npm ci --include dev

      - name: Install token-metadata-creator
        run: |
          # Download the pre-built binary for token-metadata-creator
          curl -LJO https://github.com/input-output-hk/offchain-metadata-tools/releases/download/v0.4.0.0/token-metadata-creator.tar.gz
          # Extract the binary from the tar.gz file
          tar -xzf token-metadata-creator.tar.gz
          # Make the binary executable
          chmod +x token-metadata-creator
          # Create the directory if it doesn't exist
          mkdir -p $HOME/.local/bin/
          # Move the binary to the specified directory
          mv token-metadata-creator $HOME/.local/bin/

      - name: Inject secrets
        run: |
          sed -i "s|{{ vault('token-minter/blockfrost').api_key }}|$BLOCKFROST_KEY|g" config/local.yml.j2
          sed -i "s|{{ vault('token-minter/wallets').owner }}|$OWNER_KEY|g" config/local.yml.j2
          sed -i "s|{{ vault('token-minter/wallets').minter }}|$WALLET_SEED|g" config/local.yml.j2
          mv config/local.yml.j2 config/local.yml
        env:
          BLOCKFROST_KEY: ${{ secrets.BLOCKFROST_PREVIEW_KEY }}
          OWNER_KEY: ed25519_sk13644lrp7erfrqu3k5k29kv9stqzudfchxttem5773sef58s9yanspdnhlf
          WALLET_SEED: ${{ secrets.INTEGRATION_WALLET }}

      - name: Create fake vault-cli
        run: |
          echo "#!/bin/bash" > /usr/local/bin/vault-cli
          echo "cat config/local.yml" >> /usr/local/bin/vault-cli
          chmod +x /usr/local/bin/vault-cli

      - name: Run tests
        run: npx ava

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1

      - name: Install dependencies
        run: npm install --include dev

      - name: Lint
        run: npm run lint
